basePath: /api/v1
definitions:
  handlers.User:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: 这是一个使用 Gin + Swaggo 的示例项目
  title: Swagger 示例项目
  version: "1.0"
paths:
  /user/{id}:
    get:
      consumes:
      - application/json
      description: 通过用户 ID 获取用户信息
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.User'
      summary: 获取用户
      tags:
      - 用户
swagger: "2.0"
